// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Humberto",
            "url": "https://github.com/humberto0/shopkeeper"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/humberto0/shopkeeper/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Pings the database pool to check that the API and its dependencies are up.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "status: ok",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "database unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Creates a new user account (owner or clerk).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User to register",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.registerUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.registerUserResponse"
                        }
                    },
                    "400": {
                        "description": "malformed request body",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "409": {
                        "description": "email already exists",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "422": {
                        "description": "invalid name, email, password or role",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handler.registerUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "humbertotest@shop.com"
                },
                "name": {
                    "type": "string",
                    "example": "Humberto test"
                },
                "password": {
                    "type": "string",
                    "example": "senha1234"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "owner",
                        "clerk"
                    ],
                    "example": "owner"
                }
            }
        },
        "handler.registerUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "humbertotest@shop.com"
                },
                "id": {
                    "type": "string",
                    "example": "018f1d3a-7c3e-7c3e-8b3e-7c3e7c3e7c3e"
                },
                "name": {
                    "type": "string",
                    "example": "Humberto test"
                },
                "role": {
                    "type": "string",
                    "example": "owner"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "shopkeeper API",
	Description:      "Stock and sales management API for local shop owners.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
